# SPDX-FileCopyrightText: 2026 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
      conventional:
        types:
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - release
          - style
          - test
        description: true
